source 'https://rubygems.org'

ruby '1.9.3'
gem 'rails', '3.2.13'

group :development, :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem "rspec-rails"
  gem 'launchy'
  gem 'factory_girl_rails'
  gem 'shoulda-matchers'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'thin'
gem 'mongoid'
gem 'bson_ext'
gem 'jquery-rails'
gem 'devise'
gem 'haml'
gem 'pry'
gem 'pry-nav'
gem 'rolify'
gem 'cancan'
gem 'newrelic_rpm', "~> 3.5.5.38"
gem 'switch_user'
gem 'kaminari'
gem 'json'
gem 'delayed_job_mongoid'
gem 'mongoid_slug'
gem 'jbuilder'
gem "mongoid_shortener"
gem "yab62", require: "yab62"



