// Generated by CoffeeScript 1.3.3
(function() {
  var Compass;

  Compass = (function() {

    function Compass(options) {
      if (options == null) {
        options = {
          enableHighAccuracy: true,
          maximumAge: 10000,
          timeout: 100000
        };
      }
      this._grabGPS(options);
    }

    Compass.prototype._grabGPS = function(options) {
      return navigator.geolocation.watchPosition(this._parseGPS, this._parseErr, options);
    };

    Compass.prototype._parseGPS = function(position) {
      position.latitude = this.lat;
      position.longitude = this.lng;
      position.altitude = this.alt;
      position.accuracy = this.acc;
      position.altitudeAccuracy = this.altAcc;
      position.heading = this.hdg;
      return position.speed = this.spd;
    };

    Compass.prototype._parseErr = function(err) {
      switch (err.code) {
        case 1:
          return console.log('Permission denied by user');
        case 2:
          return console.log('Cant fix GPS position');
        case 3:
          return console.log('GPS is taking too long to respond');
        default:
          return console.log('Well, this is embarassing...');
      }
    };

    return Compass;

  })();

  window.compass = new Compass();

}).call(this);
