// Generated by CoffeeScript 1.3.3
(function() {
  var Theatre;

  Theatre = (function() {

    function Theatre(_arg) {
      var backStage, firstScene, stage;
      stage = _arg.stage, firstScene = _arg.firstScene, backStage = _arg.backStage;
      if (stage == null) {
        stage = '#front_stage';
      }
      if (firstScene == null) {
        firstScene = false;
      }
      if (backStage == null) {
        backStage = '#back_stage';
      }
      $(backStage).hide();
      this.stage = $(stage);
      this.sceneHistory = [];
      if (firstScene != null) {
        this.scene = $(firstScene);
      }
    }

    Theatre.prototype.goBack = function() {
      if (this.sceneHistory.length > 0) {
        return this.perform(this.lastStage.pop());
      }
    };

    Theatre.prototype.perform = function(scene, data) {
      var new_content;
      if (data == null) {
        data = {};
      }
      if (this.scene) {
        this.sceneHistory.concat(this.scene);
      }
      this.scene = $(scene);
      this.stage.empty();
      new_content = this.render(scene, data);
      return this.stage.html($(new_content).html());
    };

    Theatre.prototype.render = function(scene, data) {
      var compiled;
      if (data == null) {
        data = {};
      }
      compiled = _.template($(scene).text());
      return compiled(data);
    };

    return Theatre;

  })();

  $(function() {
    window.radioCollar = new Theatre({
      stage: '#front_stage',
      firstScene: '#scene3'
    });
    $('#back').click(function() {
      return radioCollar.goBack();
    });
    $('#second').click(function() {
      return radioCollar.perform('#scene2');
    });
    return $('#first').click(function() {
      return radioCollar.perform('#scene1');
    });
  });

}).call(this);
