// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.server_url = 'localhost:3000/api/v1';

  $(function() {
    var _ref, _ref1, _ref2, _ref3;
    window.Place = (function(_super) {
      __extends(Place, _super);

      function Place() {
        _ref = Place.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Place.prototype.idAttribute = "_id";

      Place.prototype.initialize = function() {
        return this.set({
          title: this.get("title")
        });
      };

      Place.prototype.validate = function(attrs, optns) {
        if (!this.title) {
          return "Title is required";
        } else if (!this.lat) {
          return "Latitude is required";
        } else if (!this.lng) {
          return "Longitude is required";
        }
      };

      Place.prototype.urlRoot = server_url + "/places";

      return Place;

    })(Backbone.Model);
    window.Places = (function(_super) {
      __extends(Places, _super);

      function Places() {
        _ref1 = Places.__super__.constructor.apply(this, arguments);
        return _ref1;
      }

      Places.prototype.model = Place;

      return Places;

    })(Backbone.Collection);
    window.PlaceNewView = (function(_super) {
      __extends(PlaceNewView, _super);

      function PlaceNewView() {
        this.render = __bind(this.render, this);
        _ref2 = PlaceNewView.__super__.constructor.apply(this, arguments);
        return _ref2;
      }

      PlaceNewView.prototype.el = $('#content');

      PlaceNewView.prototype.initialize = function() {
        return this.template = templayed($("#gpsCtrlTmpl").html())(this.model);
      };

      PlaceNewView.prototype.events = {
        "click #send": "createPlace"
      };

      PlaceNewView.prototype.clear = function() {
        return this.model.destroy();
      };

      PlaceNewView.prototype.edit = function() {
        var oldTitle;
        return oldTitle = this.model.get("title");
      };

      PlaceNewView.prototype.createPlace = function(e) {
        return this.model.save();
      };

      PlaceNewView.prototype.render = function() {
        $(this.el).html(this.template);
        return this;
      };

      return PlaceNewView;

    })(Backbone.View);
    window.RadioCollarRouter = (function(_super) {
      __extends(RadioCollarRouter, _super);

      function RadioCollarRouter() {
        _ref3 = RadioCollarRouter.__super__.constructor.apply(this, arguments);
        return _ref3;
      }

      RadioCollarRouter.prototype.routes = {
        "": "home"
      };

      RadioCollarRouter.prototype.initialize = function() {
        var pl;
        pl = new Place({
          title: 'placeholder. Rendered with backbone. yay!'
        });
        return this.plvw = new PlaceNewView({
          model: pl
        });
      };

      RadioCollarRouter.prototype.home = function() {
        return this.plvw.render();
      };

      return RadioCollarRouter;

    })(Backbone.Router);
    window.App = new RadioCollarRouter();
    return Backbone.history.start();
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
