// Generated by CoffeeScript 1.6.3
(function() {
  $.support.cors = true;

  $(function() {});

  window.sendd = function(url, meth, data1) {
    return $.ajax({
      type: meth,
      url: "http://localhost:3000/api/v1/" + url,
      crossDomain: true,
      data: data1,
      dataType: "json",
      success: function(data) {
        return alert(data);
      },
      error: function(responseData, textStatus, errorThrown) {
        alert('newp!');
        debugger;
      }
    });
  };

}).call(this);

/*
//@ sourceMappingURL=auth.map
*/
