// Generated by CoffeeScript 1.3.3
(function() {

  window.datasend = function(url1, method1, data1) {
    return $.ajax({
      method: method1,
      url: "http://192.168.0.4:3000/api/v1/" + url1,
      type: 'jsonp',
      crossDomain: true,
      data: data1,
      context: document.body
    }).done(function() {
      return console.log('sent data');
    });
  };

  $.support.cors = true;

  $(function() {
    return datasend('login', 'POST', {
      email: 'rick.carlino\@gmail.com',
      password: 'password1'
    });
  });

}).call(this);
