// Generated by CoffeeScript 1.4.0
(function() {
  var updateGps;

  updateGps = function() {
    console.log('meemoo');
    if (compass.err) {
      return $('#sendName').val(compass.err);
    } else {
      $('#lat').val(compass.lat);
      return $('#lng').val(compass.lng);
    }
  };

  $(function() {
    return setInterval((function() {
      return updateGps();
    }), 1000);
  });

}).call(this);
