// Generated by CoffeeScript 1.4.0
(function() {
  var Theatre;

  Theatre = (function() {

    function Theatre(_arg) {
      var backStage, firstScene, stage;
      stage = _arg.stage, firstScene = _arg.firstScene, backStage = _arg.backStage;
      if (stage == null) {
        stage = '#front_stage';
      }
      if (firstScene == null) {
        firstScene = false;
      }
      if (backStage == null) {
        backStage = '#back_stage';
      }
      $(backStage).hide();
      this.stage = $(stage);
      this.sceneHistory = [];
      if (firstScene != null) {
        this.scene = $(firstScene);
      }
      this.stage.empty();
      this.stage.html($(firstScene).html());
    }

    Theatre.prototype.goBack = function() {
      var back, previousScene;
      back = this.sceneHistory.length - 1;
      previousScene = this.sceneHistory[back];
      this.scene = $(previousScene);
      this._render(previousScene);
      return this.sceneHistory.pop();
    };

    Theatre.prototype.perform = function(scene) {
      if (this.scene) {
        this.sceneHistory = this.sceneHistory.concat(this.scene.selector);
      }
      this.scene = $(scene);
      return this._render(scene);
    };

    Theatre.prototype._render = function(scene) {
      var _this = this;
      return this.stage.fadeOut(200, function() {
        _this.stage.hide();
        return _this.stage.html($(scene).html()).fadeIn(200);
      });
    };

    return Theatre;

  })();

  $(function() {
    return window.nav = new Theatre({
      stage: '#content',
      firstScene: '#scene1'
    });
  });

}).call(this);
